SELECT* FROM productos WHERE SECCIÓN='deportes' OR SECCIÓN='ceramica';

SELECT* FROM productos WHERE SECCIÓN='deportes' OR SECCIÓN='ceramica' ORDER BY SECCIÓN;

SELECT NOMBREARTÍCULO,PRECIO,SECCIÓN,IMPORTADO FROM productos WHERE SECCIÓN='ceramica' OR SECCIÓN='deportes' ORDER BY PRECIO;

SELECT FECHA,NOMBREARTÍCULO,CÓDIGOARTÍCULO,IMPORTADO,PAÍSDEORIGEN FROM productos WHERE SECCIÓN='deportes' OR SECCIÓN='JUGUETERÍA' ORDER BY FECHA DESC;

SELECT NOMBREARTÍCULO,CÓDIGOARTÍCULO,PAÍSDEORIGEN,FECHA FROM productos WHERE SECCIÓN='deportes' OR SECCIÓN='JUGUETERÍA'ORDER BY PAÍSDEORIGEN DESC;

SELECT NOMBREARTÍCULO,CÓDIGOARTÍCULO,PAÍSDEORIGEN,FECHA FROM productos WHERE SECCIÓN='deportes'OR SECCIÓN='JUGUETERÍA' ORDER BY FECHA DESC;

SELECT NOMBREARTÍCULO,CÓDIGOARTÍCULO,PAÍSDEORIGEN,SECCIÓN,FECHA FROM productos WHERE SECCIÓN='deportes'OR SECCIÓN='JUGUETERÍA' ORDER BY SECCIÓN,FECHA;

SELECT NOMBREARTÍCULO,PRECIO,SECCIÓN,IMPORTADO FROM productos WHERE SECCIÓN='ceramica' OR SECCIÓN='deportes' ORDER BY SECCIÓN,PRECIO;

SELECT NOMBREARTÍCULO,PRECIO,SECCIÓN,IMPORTADO FROM productos WHERE SECCIÓN='ceramica' OR SECCIÓN='deportes' ORDER BY SECCIÓN,PRECIO DESC;

SELECT NOMBREARTÍCULO,CÓDIGOARTÍCULO,SECCIÓN,PAÍSDEORIGEN,FECHA FROM productos WHERE SECCIÓN='ceramica' OR SECCIÓN='deportes' ORDER BY SECCIÓN,FECHA DESC;

SELECT NOMBREARTÍCULO,CÓDIGOARTÍCULO,SECCIÓN,PAÍSDEORIGEN,FECHA FROM productos WHERE SECCIÓN='ceramica' OR SECCIÓN='deportes' ORDER BY NOMBREARTÍCULO,SECCIÓN , FECHA DESC,PAÍSDEORIGEN;

SELECT NOMBREARTÍCULO,CÓDIGOARTÍCULO,SECCIÓN,PAÍSDEORIGEN,FECHA FROM productos WHERE SECCIÓN='ceramica' OR SECCIÓN='deportes' ORDER BY SECCIÓN, FECHA DESC, PAÍSDEORIGEN;

